# Generated by Django 5.1.3 on 2024-11-19 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='learner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.useraccount'),
        ),
    ]
